In [1]:
#importing the numpy library as np

import numpy as np

In [2]:
#arange()
#Syntax np.arange(start, stop, step,, dtype)

a = np.arange(0,15)

In [3]:
#reshape()
'''
Used to change dimensions of already declared array
 Syntax array.reshape(order)
'''
a = a.reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
#shape function to get order
#synatx array.shape

a.shape

(3, 5)

In [5]:
'''
ndim function to get dimension of array
Synatx array.ndim
'''
a.ndim

2

In [6]:
#size
#Syntax array.size

a.size

15

In [7]:
#type() to get type
#Syntax type(variable)

type(a)

numpy.ndarray

In [8]:
#dtype
#Syntax variable.dtype

a.dtype

dtype('int32')

In [9]:
#np.array([list] or (tuple))

b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [10]:
#zeros() and ones()
#Synatx np.zeros(shape) np.ones(shape)

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [12]:
#empty()
#Syntax np.empty((shape))

np.empty((1,3))

array([[1.38354482e-311, 0.00000000e+000, 2.22518658e-306]])

In [13]:
'''
eye() for identity matrix
Synatx np.eye(r,c,k,dtype)
k=0 default i.e, diagonal
'''
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
'''
diag() to extract or to give diagonal elements
Syntax np.diag(a,k)
'''
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

# Slicing and Indexing

In [15]:
a = np.arange(20)

#slicing array[start:stop:step]

a[::]       #prints complete array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
a[10::]     #prints values after index 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
a[:10:]     #prints values after index upto 9 (i.e, 10-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[::-1]     #starts printing from last postion 

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [19]:
a[-8:17:1]  #negative starting values are allowed for start

array([12, 13, 14, 15, 16])

# Array operations

In [20]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [21]:
b = np.array([0,10,20,30,40])
b

array([ 0, 10, 20, 30, 40])

In [22]:
c = a + b
c

array([ 1, 12, 23, 34, 45])

In [23]:
a = a - 10
a

array([-9, -8, -7, -6, -5])

In [24]:
c = a + 10
c

array([1, 2, 3, 4, 5])

In [25]:
np.square(b)

array([   0,  100,  400,  900, 1600], dtype=int32)

In [26]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
#sum() 
#Syntax variable.sum(axis='None',dtype)
b.sum()

105

In [28]:
b.sum(axis=0)

array([15, 18, 21, 24, 27])

In [29]:
b.sum(axis=1)

array([10, 35, 60])

In [30]:
b.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [31]:
a = np.arange(15).reshape((3,5)) 
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
b = (a % 3 == 0) 
b

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [33]:
a[b]

array([ 0,  3,  6,  9, 12])